# Compose a postgres database together with the extension pgvector
services:
  db:
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - pgdata:/var/lib/postgresql/data  # Added volume for data persistence

volumes:
  pgdata: {}  # Define the volume